version: "3.7"

services:
  ghost:
    container_name: blog_ghost
    image: ghost:4-alpine
    restart: unless-stopped
    ports:
      - 3001:2368
    volumes:
      - ./docker/ghost_data:/var/lib/ghost/content
    environment:
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: root
      database__connection__password: MG%ShdgC!Nzk
      database__connection__database: ghost
      url: http://localhost:3001
    depends_on:
      - ghost_db
    extra_hosts:
      - host.docker.internal:host-gateway

  ghost_db:
    container_name: blog_db
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MG%ShdgC!Nzk

  instalink_db:
    container_name: instalink_db
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb_data:/data/db
